apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: eto-pet
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s
    scrape_configs:
      - job_name: 'eto-pet'
        static_configs:
          - targets: ['backend:8080']
